ARG NODE_IMAGE=dockerhub.webbfontaine.am/node:18-slim
ARG NGINX_IMAGE=dockerhub.webbfontaine.am/nginx-static
FROM ${NODE_IMAGE} AS builder

RUN apt-get update && apt-get install -y git

WORKDIR /app

ARG NEXUS_USER=developer
ARG NEXUS_PASS
ARG NEXUS_EMAIL=hayk.yeghiazaryan@webbfontaine.com
ARG NEXUS_REGISTRY=https://repo.webbfontaine.com/nexus/repository/wf-npm-all/
ARG NEXUS_SCOPE=@wf,@cwb,@pl

RUN yarn global add npm-cli-login
RUN yarn global add npm-cli-adduser

COPY ./wf-registry-login.sh .
RUN chmod +x ./wf-registry-login.sh
RUN ./wf-registry-login.sh -U ${NEXUS_USER} -P ${NEXUS_PASS} -E ${NEXUS_EMAIL} -R ${NEXUS_REGISTRY} -S ${NEXUS_SCOPE}

# Install dependencies and cache the layer until dependencies are changes
COPY ["package.json", "yarn.lock", "./"]
RUN yarn install

# Copy source code
COPY ./ ./

ARG SONAR_HOST_URL=https://sonar.webbfontaine.com
ARG SONAR_AUTH_TOKEN
ARG SONAR_PROJECT_KEY
ARG SONAR_BRANCH

# RUN npm run test

RUN yarn sonar -- sonar.host.url=${SONAR_HOST_URL} sonar.login=${SONAR_AUTH_TOKEN} sonar.projectKey=${SONAR_PROJECT_KEY} sonar.branch.name=${SONAR_BRANCH} sonar.qualitygate.wait=true

RUN yarn build