export const APPNAME = 'LPCO';

export const DEFAULT_COUNT = 10;
export const PAGINATION_LIMIT = 10;

export const MANUAL = 'MANUAL';
export const NUM_OF_DAYS = 'NUM_OF_DAYS';
export const PERMANENT = 'PERMANENT';
export const NATIONAL_CURRENCY = 'XOF';
export const ALL_DATA = 'ALL';

export enum SortDirection {
  DESC = 'DESC',
  ASC = 'ASC',
}

export enum QuotaType {
  UOM = 'UOM',
  VALUE = 'VALUE',
  NET_MASS = 'NET_MASS',
  GROSS_MASS = 'GROSS_MASS',
  UNLIMITED = 'UNLIMITED',
  TAX = 'TAX',
}

export enum ApplicationRoles {
  ROLE_LPCO2_ADMIN_VIEWER = 'ROLE_LPCO2_ADMIN_VIEWER',
  ROLE_LPCO2_TRADER = 'ROLE_LPCO2_TRADER',
  ROLE_LPCO2_ADMINISTRATOR = 'ROLE_LPCO2_ADMINISTRATOR',
  ROLE_LPCO2_GOVERNMENT_OFFICER = 'ROLE_LPCO2_GOVERNMENT_OFFICER',
  ROLE_LPCO2_GOVERNMENT_SENIOR_OFFICER = 'ROLE_LPCO2_GOVERNMENT_SENIOR_OFFICER',
  ROLE_LPCO2_MINISTRY_ADMIN_VIEWER = 'ROLE_LPCO2_MINISTRY_ADMIN_VIEWER',
  ROLE_LPCO2_CASHIER = 'ROLE_LPCO2_CASHIER',
  ROLE_LPCO2_MINISTRY_ADMINISTRATOR = 'ROLE_LPCO2_MINISTRY_ADMINISTRATOR',
  ROLE_LPCO2_DECLARANT = 'ROLE_LPCO2_DECLARANT',
}
