export const licensePropsDefaultValues = {
  licenseType: null,
  userReferenceNumber: '',
  requestNumber: '',
  requestDate: null,
  approvalReference: '',
  approvalDate: null,
  validFrom: null,
  validTo: null,
  countryOfDestinationCode: null,
  typeOfUse: null,
  declarantCode: '',
  declarantName: '',
  companyCode: null,
  companyPhone: '',
  companyEmail: '',
  invoiceCurrencyCode: null,
  invoiceAmountInForeignCurrency: null,
  invoiceAmountInNationalCurrency: null,
};
