const POPUP_CLOSE_BUTTON_TEXT = 'Close';
const OPERATION_UPDATE_BUTTON_TEXT = 'Update';
const OPERATION_ADD_BUTTON_TEXT = 'Add';

export default {
  POPUP_CLOSE_BUTTON_TEXT,
  OPERATION_UPDATE_BUTTON_TEXT,
  OPERATION_ADD_BUTTON_TEXT,
};
