import {
  additionalFieldsAdapter,
  approvalsAdapter,
  documentsAdapter,
  feesAdapter,
  feesAdapterForExtend,
  transitionsAdapter,
} from './entityAdapters';

import { feeMode } from './types';

import type { IFeatureFlagsProps, ILicenseTypeByCodeProps, LicenseTypeState } from './types';
import { MANUAL, NUM_OF_DAYS, QuotaType } from '../../constatnts';

export const defaultLicenseTypeByCode: ILicenseTypeByCodeProps = {
  licenseTypeCode: '',
  licenseTypeName: '',
  licenseTypeNameInNationalLang: '',
  licenseTypeNature: '',
  applicationFeeMode: feeMode.NONE,
  extensionFeeMode: feeMode.NONE,
  dov: '',
  eov: null,
  ministryCode: '',
  departmentCode: '',
  tariffListCode: '',
  relatedProducts: '',
  flow: 'IM',
  paymentFlow: 'AFTER',
  typeOfUse: 'SINGLE',
  startDateValidityType: NUM_OF_DAYS,
  endDateValidityType: MANUAL,
  validityPeriod: 0,
  noOfDaysBeforeValidFrom: 0,
  noOfDaysBeforeValidTo: 0,
  noOfAllowableExtension: 0,
  maxNumOfDaysForExtension: 0,
  quotaType: '',
  quotaTaxCode: '',
  enabledQuotas: [QuotaType.UOM, QuotaType.VALUE, QuotaType.NET_MASS, QuotaType.GROSS_MASS, QuotaType.UNLIMITED],
  printStatuses: [],
  sigAndStampsName: null,
};

export const defaultLicenseTypeFeatureFlagsByCode: IFeatureFlagsProps = {
  flowEnabled: true,
  relatedProductsEnabled: false,
  declarantEnabled: false,
  typeOfUseEnabled: false,
  countryOfExportOrImportEnabled: true,
  termOfDeliveryEnabled: false,
  placeOfLoadingEnabled: false,
  placeOfUnloadingEnabled: false,
  contactPersonEnabled: false,
  departmentOfficeEnabled: false,
  entryExitPointEnabled: false,
  listOfBeneficiariesEnabled: false,
  suspendOpEnabled: true,
  cancelOpEnabled: true,
  updateApproveOpEnabled: true,
  packageManagementTableEnabled: false,
  treatmentTableEnabled: false,
  hsCodeEnabled: true,
  extendBeforeExpirationEnabled: false,
  extendAfterExpirationEnabled: false,
  fixFee: false,
  fixFeeForExtend: false,
  packageManagementEnabled: false,
  invoiceValueManagementEnabled: false,
  itemWeightManagementEnabled: false,
  addItemOnQueriedEnabled: false,
  editItemOnQueriedEnabled: false,
  deleteItemOnQueriedEnabled: false,
  addItemOnOgaEditEnabled: false,
  editItemOnOgaEditEnabled: false,
  deleteItemOnOgaEditEnabled: false,
  requestedAndApprovedAmountEnabled: false,
  remainingAmountEnabled: false,
};

export const initialState: LicenseTypeState = {
  licenseTypeByCode: defaultLicenseTypeByCode,
  licenseTypeFeatureFlagsByCode: defaultLicenseTypeFeatureFlagsByCode,
  licenseTypeAprovalsByCode: approvalsAdapter.getInitialState(),
  licenseTypeApTransitionsByCode: transitionsAdapter.getInitialState(),
  licenseTypeFeesByCode: feesAdapter.getInitialState(),
  licenseTypeFeesForExtendByCode: feesAdapterForExtend.getInitialState(),
  licenseTypeAttDocumentsByCode: documentsAdapter.getInitialState(),
  licenseTypeAdditionalFieldsByCode: additionalFieldsAdapter.getInitialState(),
};
